apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    password: 12345678
    jsonData:
      version: Flux
      organization: MyOrg
      defaultBucket: glances
      tlsSkipVerify: true
    secureJsonData:
      token: MyToken